### ISSUE TITLE
Undefined method random

### ISSUE THREAD

**Issue by gdjmck** [christofferholmstedt/opencv-wrapper-egbis#3]
In the segment-image.cpp, i come across an error from the compiler saying that the method 'random' is undefined.
Is that i just need to write a function that generates an integer from 0 to 255 will be alright?

**Comment by christofferholmstedt** [comment]
Good question, I haven't used this application in a long time. I will see if I get some time to try it out myself with a new compiler.

**Comment by christofferholmstedt** [comment]
Can you please add more information about how you went about compiling and some information about compiler version and OS version?

I just tried with Ubuntu 16.04.2 and didn't get any warnings. Maybe it is just a compiler flag I'm not using?

I've updated the README instructions now for Ubuntu 16.04.2, no big changes since 14.04.2

### I'm using the following:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Linux 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by burak-yildizoz** [comment]
Just replace `random()` with `rand()`.

Casting to `uchar` makes it between 0-255, and `stdlib` is already included in the header file.

**Comment by christofferholmstedt** [comment]
This should have been fixed now with the changes done by @burak-yildizoz, thank you!
